Repository Gaichuuu/gaichu-tcg-database, pull requests merged in 2025-07, with the labels that each got.

#71 Add set overview and image
  data/sets.json
  firestoreScript/scriptDatabase.cjs
  package.json
  src/__test__/__mock__/cardJson.ts
  src/__test__/__mock__/setJson.ts
  src/__test__/services/CollectionSetService.test.ts
  src/__test__/services/JsonCollectionCardService.test.ts
  src/__test__/services/JsonCollectionSeriesService.test.ts
  src/components/ListComponent/CardListComponent.tsx
  src/components/ListComponent/SeriesListComponent.tsx
  src/components/ListComponent/SetListConponent.tsx
  src/hooks/useCollection.tsx
  src/pages/SeriesPage.tsx
  src/pages/SetPage.tsx
  src/pages/TcgSeriesPage.tsx
  src/services/CollectionSetService.tsx
  src/services/JsonCollectionCardService.tsx
  src/services/JsonCollectionSeriesService.tsx
  src/services/JsonCollectionSetService.tsx
  src/types/CollectionSet.tsx
  src/types/MergedCollection.tsx
  src/utils/TimeUtils.tsx
Labels: improvement

#73 Increases the size of the set tile images
  src/components/ListComponent/SetListConponent.tsx
Labels: improvement, UI

#81 Starting the README updates for 1.0 release
  README.md
  src/components/Footer.tsx
Labels: documentation

#82 Release updates
  README.md
  package-lock.json
  package.json
  src/components/Footer.tsx
Labels: documentation
