Repository Gaichuuu/gaichu-tcg-database, pull requests merged in 2025-05, with the labels that each got.

#45 Local database
  .gitignore
  data/cards.json
  data/cards.schema.json
  data/illustrators.json
  data/rarity.json
  data/series.json
  data/sets.json
  data/type.json
  package-lock.json
  package.json
  scripts/exportCollections.cjs
Labels: improvement

#46 Database schema
  .gitignore
  .vscode/settings.json
  data/cards.schema.json
  data/illustrators.schema.json
  data/rarity.schema.json
  data/series.schema.json
  data/sets.schema.json
  data/type.schema.json
Labels: improvement

#47 Hover tooltip
  package-lock.json
  package.json
  src/components/ListComponens/CardListComponent.tsx
  src/components/TileComponents/HoverTooltip.tsx
Labels: UI

#48 Updated translations for names and attacks
  data/cards.json
Labels: bug

#52 add script for importing data from json to firebase database
  config/FirebaseConfig.tsx
  firestoreScript/databaseConstants.cjs
  firestoreScript/exportCollections.cjs
  firestoreScript/importCollections.cjs
  firestoreScript/scriptDatabase.cjs
  package.json
  src/services/CollectionCardService.tsx
  src/services/CollectionSeriesService.tsx
  src/services/CollectionSetService.tsx
  tsconfig.app.json
Labels: improvement

#53 Add preview and next button in card detail view
  data/cards.json
  data/cards.schema.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/ButtonComponents/CardDetailPagingButton.tsx
  src/components/ListComponens/CardListComponent.tsx
  src/components/ListComponens/SetListConponent.tsx
  src/hooks/getCollection.tsx
  src/hooks/useCollectionCard.tsx
  src/pages/CardDetailPage.tsx
  src/services/AppResult.tsx
  src/services/CollectionCardService.tsx
  src/services/JsonCollectionCardService.tsx
  src/services/JsonCollectionSeriesService.tsx
  src/services/JsonCollectionSetService.tsx
  src/services/Result.tsx
  src/types/CollectionCard.tsx
Labels: improvement

#55 Long card name truncate
  src/components/ButtonComponents/CardDetailPagingButton.tsx
  src/components/ListComponens/CardListComponent.tsx
Labels: bug
